name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v18.17.1
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.1"
      - run: npm install
      - run: npm test
